      program RINPUT
C==============================================================RINPUT
      implicit none
      integer ncmp
      parameter (ncmp=2)
      INTEGER N,icmp,itmp,i,j
C----------
      DOUBLE PRECISION tenth,
     1     SRLO,SR,SRDT,VISTAB,CNDTAB,VISLO,CNDLO,VISDT,CNDDT
C
C==============================================================RINPUT
C    SET THE PROPERTIES FOR SPECIES NOT DEFINED IN SUBROUTINE HOT
C    THIS PART IS TO BE REPLACED BY READING DATA FROM DATA FILE
C    GENERATED BY THE PROPERTY CALCULATION PROGRAM
C----------
      DIMENSION SR(21,NCMP),VISTAB(21,NCMP),CNDTAB(21,NCMP)
      double precision ssubr(201,ncmp),vis(201,ncmp),cnd(201,ncmp)
C
C==============================================================RINPUT
C     RADIATION LOSS OF ARGON PLASMA
C--------------------------------------------------------------RINPUT
c     DATA (SR(N,1),N=1,21)
c    1  /0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00,
c    2   0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 4.00D+07,
c    3   3.53D+08, 1.12D+09, 3.31D+09, 7.86D+09, 1.37D+10,
c    4   1.92D+10, 2.27D+10, 2.26D+10, 2.26D+10, 2.63D+10, 3.11D+10/
C==============================================================RINPUT
C     ARGON-HELIUM (100:47) PLASMA TRANSPORT PROPERTY DATA,
C     OBTAINED FROM THE UNIVERSITY OF MINNESOTA
C     INTERVALS ARE T=1000(N-1). UNITS ARE IN CGS.
C--------------------------------------------------------------RINPUT
C---------- COPIED FROM AR DATA FOR SR
      DATA (SR(N,1),N=1,21)
     1  /0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00,
     2   0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 4.00D+07,
     3   3.53D+08, 1.12D+09, 3.31D+09, 7.86D+09, 1.37D+10,
     4   1.92D+10, 2.27D+10, 2.26D+10, 2.26D+10, 2.63D+10, 3.11D+10/
C----------
      DATA (VISTAB(N,1),N=1,21)
     1  /5.00D-04, 1.59D-03, 2.47D-03, 3.13D-03, 3.70D-03,
     2   4.22D-03, 4.70D-03, 5.15D-03, 5.57D-03, 5.96D-03,
     3   6.24D-03, 6.28D-03, 5.97D-03, 5.44D-03, 4.97D-03,
     4   4.69D-03, 4.58D-03, 4.58D-03, 4.59D-03, 4.55D-03, 4.37D-03/
C---------- TRANSLATIONAL PART ONLY
      DATA (CNDTAB(N,1),N=1,21)
     1  /4.00D+04, 6.90D+04, 9.94D+04, 1.22D+05, 1.42D+05, 
     2   1.60D+05, 1.76D+05, 1.91D+05, 2.08D+05, 2.30D+05,
     3   2.60D+05, 2.97D+05, 3.39D+05, 3.87D+05, 4.36D+05,
     4   4.83D+05, 5.22D+05, 5.53D+05, 5.80D+05, 6.03D+05, 6.18D+05/
C==============================================================RINPUT
C     PROPERTIES OF AIR PLASMA
C--------------------------------------------------------------RINPUT
      DATA (SR(N,2),N=1,21)
     1  /0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00,
     2   0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00,
     3   0.00D+00, 1.50D+10, 3.00D+10, 5.00D+10, 7.00D+10,
     4   1.05D+11, 1.40D+11, 1.40D+11, 1.40D+11, 1.40D+11, 1.40D+11/
C----------
      DATA (VISTAB(N,2),N=1,21)
     1  /1.06D-04, 4.00D-04, 6.60D-04, 8.80D-04, 1.06D-03,
     2   1.30D-03, 1.64D-03, 2.00D-03, 2.30D-03, 2.56D-03,
     3   2.68D-03, 2.64D-03, 2.48D-03, 2.18D-03, 1.76D-03,
     4   1.22D-03, 5.60D-04, 2.69D-04, 2.02D-04, 1.68D-04, 1.53D-04/
C---------- TRANSLATIONAL PART ONLY
      DATA (CNDTAB(N,2),N=1,21)
     1  /1.00D+03, 3.18D+03, 1.04D+04, 1.47D+04, 2.01D+04, 
     2   2.51D+04, 3.22D+04, 4.60D+04, 6.58D+04, 8.84D+04,
     3   1.13D+05, 1.36D+05, 1.56D+05, 1.72D+05, 1.89D+05,
     4   2.10D+05, 2.34D+05, 2.62D+05, 2.91D+05, 3.24D+05, 3.58D+05/
C==============================================================RINPUT
C     PROPERTIES OF N2 PLASMA
C--------------------------------------------------------------RINPUT
c     DATA (SR(N,2),N=1,21)
c    1  /0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00,
c    2   0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00, 0.00D+00,
c    3   0.00D+00, 1.13D+10, 1.71D+10, 2.78D+10, 3.86D+10,
c    4   5.02D+10, 5.65D+10, 6.11D+10, 6.35D+10, 6.30D+10, 6.30D+10/
C----------
c     DATA (VISTAB(N,2),N=1,21)
c    1  /1.06D-04, 4.06D-04, 6.78D-04, 9.23D-04, 1.15D-03,
c    2   1.38D-03, 1.65D-03, 1.96D-03, 2.17D-03, 2.32D-03,
c    3   2.40D-03, 2.30D-03, 1.96D-03, 1.47D-03, 9.90D-04,
c    4   6.28D-04, 3.99D-04, 2.69D-04, 2.02D-04, 1.68D-04, 1.53D-04/
C---------- TRANSLATIONAL PART ONLY
c     DATA (CNDTAB(N,2),N=1,21)
c    1  /1.07D+03, 6.23D+03, 1.12D+04, 1.55D+04, 1.95D+04,
c    2   2.38D+04, 3.06D+04, 4.12D+04, 5.20D+04, 6.56D+04,
c    3   8.28D+04, 9.95D+04, 1.13D+05, 1.27D+05, 1.43D+05,
c    4   1.62D+05, 1.85D+05, 2.10D+05, 2.36D+05, 2.64D+05, 2.94D+05/
C--------------------------------------------------------------RINPUT
C     IF INCOMP=1, VIS SHOULD BE CONSTANT.
C------------------------- FILL TRANSPORT PROPERTY TABLES -----RINPUT
       tenth=0.1d0
      DO 140 ICMP=1,ncmp
      ITMP=1
      DO 130 I=1,20
      SRLO=SR(I,ICMP)
      SRDT=(SR(I+1,ICMP)-SR(I,ICMP))*TENTH
      VISLO=VISTAB(I,ICMP)
      VISDT=(VISTAB(I+1,ICMP)-VISTAB(I,ICMP))*TENTH
      CNDLO=CNDTAB(I,ICMP)
      CNDDT=(CNDTAB(I+1,ICMP)-CNDTAB(I,ICMP))*TENTH
        DO 120 J=1,10
        SSUBR(ITMP,ICMP)=SRLO+DBLE(J-1)*SRDT
        ssubr(itmp,1)=ssubr(itmp,1)*100.0d0/147.0d0
          VIS(ITMP,ICMP)=VISLO+DBLE(J-1)*VISDT
          CND(ITMP,ICMP)=CNDLO+DBLE(J-1)*CNDDT
        ITMP=ITMP+1
  120   CONTINUE
  130 CONTINUE
      SSUBR(ITMP,ICMP)=SR(21,ICMP)
        ssubr(itmp,1)=ssubr(itmp,1)*100.0d0/147.0d0
        VIS(ITMP,ICMP)=VISTAB(21,ICMP)
        CND(ITMP,ICMP)=CNDTAB(21,ICMP)
  140 CONTINUE
C==============================================================RINPUT
      open (unit=21,file='Ar100He47.V',status='unknown')
      open (unit=22,file='Ar100He47.K',status='unknown')
      open (unit=23,file='Ar100He47.R',status='unknown')
      open (unit=24,file='Air.V',status='unknown')
      open (unit=25,file='Air.K',status='unknown')
      open (unit=26,file='Air.R',status='unknown')
      write(21,2000) (vis(n,1),n=1,201)
      write(22,2000) (cnd(n,1),n=1,201)
      write(23,2000) (ssubr(n,1),n=1,201)
      write(24,2000) (vis(n,2),n=1,201)
      write(25,2000) (cnd(n,2),n=1,201)
      write(26,2000) (ssubr(n,2),n=1,201)
 2000 format(41(5x,'&',1x,5(1x,p1d10.4,','),/))
C==============================================================RINPUT
      stop
      END
