      INTEGER NGRID,NHALF,NNP   
      PARAMETER(NHALF=50,NNP=15000)
      PARAMETER(NGRID=NHALF+NHALF+NHALF)
      INTEGER NMGD,MGD,NGD,LGD,NCS
      COMMON /INTGEOM/NMGD,MGD,NGD,LGD,NCS
C 
      DOUBLE PRECISION Y1C,Y2C,Y3C,Y1B,Y2B,Y3B,
     &       DLY1,DLY2,DLY3
      COMMON /GEOMPTC/Y1C(NHALF),Y2C(NHALF),Y3C(NHALF),
     &       Y1B(NHALF),Y2B(NHALF),Y3B(NHALF),
     &       DLY1(NHALF),DLY2(NHALF),DLY3(NHALF)
C
      DOUBLE PRECISION TPCD,RD,RM,RRS,VI,VIRS,DRD
      INTEGER SOLVS,SOLVL,SOLVRS
      COMMON /FIELDPTC/TPCD(NNP,NGRID),RD(NNP),RM(NNP),RRS(NNP),VI(NNP),
     &        VIRS(NNP),SOLVS(NNP),SOLVL(NNP),SOLVRS(NNP),DRD(NNP)
C  
      DOUBLE PRECISION PT1,PT2,PT3
      COMMON /CONTROL/PT1,PT2,PT3
