*DECK EPILOG
C
C=================================================================EPILOG
C
C     EPILOGUE
C                   ..... DEFINITIONS OF VARIABLES IN COMMON BLOCKS
C
C=================================================================EPILOG
C     CONVENTIONS USED
C=================================================================EPILOG
C     ^ = SUPERSCRIPT
C     _ = SUBSCRIPT
C     -> = CONVERTED TO
C-----------------------------------------------------------------EPILOG
C     LB = LEFT BOUNDARY OF COMPUTATIONAL DOMAIN
C     RB = RIGHT BOUNDARY OF COMPUTATIONAL DOMAIN
C     DB = DERRIERE BOUNDARY OF COMPUTATIONAL DOMAIN
C     FB = FRONT BOUNDARY OF COMPUTATIONAL DOMAIN
C     BB = BOTTOM BOUNDARY OF COMPUTATIONAL DOMAIN
C     TB = TOP BOUNDARY OF COMPUTATIONAL DOMAIN
C     BC = BOUNDARY CONDITION
C=================================================================EPILOG
C     REFERENCES
C=================================================================EPILOG
C     LAVA1 = J. D. RAMSHAW AND C. H. CHANG, PLASMA CHEM. PLASMA PROCESS
C             12, P. 299 (1992).
C     KIVA1 = A. A. AMSDEN, J. D. RAMSHAW, P. J. O'ROURKE, AND J. K.
C             DUKOWICZ, KIVA: A COMPUTER PROGRAM FOR TWO- AND
C             THREE-DIMENSIONAL FLUID FLOWS WITH CHEMICAL REACTIONS AND
C             FUEL SPRAYS, REPORT LA-10245-MS, LOS ALAMOS NATIONAL
C             LABORATORY, FEB, 1985.
C     KIVA2 = A. A. AMSDEN, P. J. O'ROURKE, AND T. D. BUTLER, KIVA2:
C             A COMPUTER PROGRAM FOR CHEMICALLY REACTIVE FLOWS AND FUEL
C             SPRAYS, REPORT LA-911560-MS, LOS ALAMOS NATIONAL LABORATORY,
C             MAY, 1989.
C     APACHE = J. D. RAMSHAW AND J. K. DUKOWICZ, APACHE: A GENERALIZED-MESH
C              EULERIAN COMPUTER CODE FOR MULTICOMPONENT CHEMICALLY
C              REACTIVE FLUID FLOW, REPORT LA-7427 LOS ALAMOS SCIENTIFIC
C              LABORATORY, JAN, 1979.
C=================================================================EPILOG
C     ALL UNITS ARE CGS, UNLESS SPECIFIED OTHERWISE
C=================================================================EPILOG
C
C     PARAMETERS
C
C-----------------------------------------------------------------EPILOG
C     NXT = (I1-1)*2+NX
C     NYT = (J1-1)*2+NY
C     NZT = (K1-1)*2+NZ
C     NSP = NUMBER OF SPECIES >= 1
C     LNRK = NUMBER OF SLOW KINETIC CHEMICAL REACTIONS >= 1
C     LNRE = NUMBER OF FAST KINETIC OR EQUILIBRIUM CHEMICAL REACTIONS >= 1
C     NIT = ARRAY DIMENSION FOR THERMOPHYSICAL OR TRANSPORT PROPERTIES
C     NCMP = NUMBER OF COMPONENTS USED IN TRANSPORT PROPERTIES
C     NPAR = NUMBER OF COMPUTATIONAL PARTICLES >= 1
C     LNOZ = NUMBER OF PARTICLE INJECTION NOZZLES >= 1
C     NSIZE = ARRAY DIMENSION OF PARTICLE SIZE DISTRIBUTION >= 1
C     N3 = NXT*NYT*NZT
C     NLR = NYT*NZT
C     NDF = NXT*NZT
C     NBT = NXT*NYT
C=================================================================EPILOG
C
C     MAIN VARIABLES SAVED IN DUMP
C
C=================================================================EPILOG
C     CONTROL PARAMETERS
C-----------------------------------------------------------------EPILOG
C     ADC = ALPHA_0 IN EQ. (41) OF LAVA1
C     BDC = BETA_0 IN EQ. (41) OF LAVA1
C     TIME = TIME
C     TIMOVI = NEAREST FUTURE TIME TO GENERATE MOVIE FILES AND RESTART
C              DUMP FILE
C     DTOLD(N3) = DT AT OLD TIME
C     INCOMP = INCOMPRESSIBLE FLOW OPTION, 0 : OFF, 1 : ON
C     ISWIRL = SWIRL FLOW OPTION, 0 : OFF, 1 : ON
C     ICYL = CYLINDRICAL COORDINATES OPTION, 0 : OFF, 1 : ON
C     NODIFF = FLAG TO TURN OFF DIFFUSION,
C              0 : DIFFUSION ON, 1 : DIFFUSION OFF
C     NLTE = NON-LTE OPTION, 0 : LTE, >= 1 : NON-LTE
C     NCYC = CYCLE NUMBER
C     NMJ = MOVIE FRAME NUMBER
C=================================================================EPILOG
C     MESH VARIABLES
C-----------------------------------------------------------------EPILOG
C     XL = SIZE OF COMPUTATIONAL DOMAIN IN X DIRECTION
C     YL = SIZE OF COMPUTATIONAL DOMAIN IN Y DIRECTION
C     ZL = SIZE OF COMPUTATIONAL DOMAIN IN Z DIRECTION
C     DX = COMPUTATIONAL CELL SIZE IN X DIRECTION
C     DY = COMPUTATIONAL CELL SIZE IN Y DIRECTION
C     DZ = COMPUTATIONAL CELL SIZE IN Z DIRECTION
C     RDX = 1/DX
C     RDY = 1/DY
C     RDZ = 1/DZ
C     XC = X COORDINATE OF CELL CENTER
C     X = X COORDINATE OF RIGHT CELL FACE
C     Y = Y COORDINATE OF FRONT CELL FACE
C     Z = Z COORDINATE OF TOP CELL FACE
C     AREA = DX*DY*DZ
C     VOL = AREA (FOR 3-D), = 2*PI*XC*DX*DY (FOR 2-D)
C     HRDXCR = 1/(DX(IC)+DX(IC+1))
C     HRDYCF = 1/(DY(IC)+DY(IC+NXT))
C     HRDZCT = 1/(DZ(IC)+DZ(IC+NXYT))
C     I1 = LEFTMOST CELL IN X DIRECTION INCLUDING GHOST CELLS
C     I2 = RIGHTMOST CELL IN X DIRECTION INCLUDING GHOST CELLS
C     J1 = REARMOST CELL IN X DIRECTION INCLUDING GHOST CELLS
C     J2 = FRONTMOST CELL IN X DIRECTION INCLUDING GHOST CELLS
C     K1 = BOTTOMMOST CELL IN X DIRECTION INCLUDING GHOST CELLS
C     K2 = TOPMOST CELL IN X DIRECTION INCLUDING GHOST CELLS
C     IC1U = STARTING CELL INDEX FOR U MOMENTUM = 1+(J1-1)*NXT+(K1-1)*NXYT
C     IC1V = STARTING CELL INDEX FOR V MOMENTUM = I1+(K1-1)*NXYT
C     IC1W = STARTING CELL INDEX FOR W MOMENTUM = I1+(J1-1)*NXT
C     IC1 = STARTING CELL INDEX FOR CELL CENTERED VARIABLES
C         = I1+(J1-1)*NXT+(K1-1)*NXYT
C     IC2 = STARTING CELL INDEX FOR CELL CENTERED VARIABLES
C         = I2+(J2-1)*NXT+(K2-1)*NXYT
C     NX = NUMBER OF COMPUTATIONAL CELLS IN XL >= 1
C     NY = NUMBER OF COMPUTATIONAL CELLS IN YL >= 1
C     NZ = NUMBER OF COMPUTATIONAL CELLS IN ZL >= 1
C     NXYT = NXT*NYT
C     NXYZT = NXT*NYT*NZT
C     IGRIDX = 0 : UNIFORM GRID IN X DIRECTION
C            = 1 : USER-SPECIFIED GRID (IN USERX) IN X DIRECTION
C     IGRIDY = 0 : UNIFORM GRID IN Y DIRECTION
C            = 1 : USER-SPECIFIED GRID (IN USERY) IN Y DIRECTION
C     IGRIDZ = 0 : UNIFORM GRID IN Z DIRECTION
C            = 1 : USER-SPECIFIED GRID (IN USERZ) IN Z DIRECTION
C     NIT1 = NIT-2
C     NXS = X(NXS) IS THE LB OF COMPUTATIONAL DOMAIN
C     NXL = X(NXL) IS THE RB OF COMPUTATIONAL DOMAIN
C     NYS = Y(NYS) IS THE DB OF COMPUTATIONAL DOMAIN
C     NYL = Y(NYL) IS THE FB OF COMPUTATIONAL DOMAIN
C     NZS = Z(NZS) IS THE BB OF COMPUTATIONAL DOMAIN
C     NZL = Z(NZL) IS THE TB OF COMPUTATIONAL DOMAIN
C=================================================================EPILOG
C     R FACTORS
C-----------------------------------------------------------------EPILOG
C     RC = R FACTOR AT CELL CENTER, DEFINED IN EQ. (1) OF LAVA1
C     RR = R FACTOR AT RIGHT CELL FACE
C     RF = R FACTOR AT FRONT CELL FACE
C     RT = R FACTOR AT TOP CELL FACE
C     RRC = 1/RC
C=================================================================EPILOG
C     MAIN VARIABLES
C-----------------------------------------------------------------EPILOG
C     U = VELOCITY IN X DIRECTION
C     V = VELOCITY IN Y DIRECTION
C     W = VELOCITY IN Z DIRECTION, SWIRL VELOCITY WHEN ISWIRL = 1
C     UN = U AT OLD TIME
C     VN = V AT OLD TIME
C     WN = W AT OLD TIME
C     RORU = RO*R*U
C     RORV = RO*R*V
C     RORW = RO*R*W
C     ROE = RO*E, E = SPECIFIC INTERNAL ENERGY OF MIXTURE
C     ROEN = ROE AT OLD TIME
C     ROER = RO*E*R
C     TEMP = TEMPERATURE
C     ROEE = RO*E_E, E_E = SPECIFIC INTERNAL ENERGY OF FREE ELECTRONS
C     ROEEN = ROEE AT OLD TIME
C     ROEER = RO*E_E*R
C     TE = ELECTRON TEMPERATURE
C     RO = TOTAL DENSITY
C     RON = RO AT OLD TIME
C     SPD = SPECIES DENSITY
C     SPDR = SPD*R
C     SPDN = SPD AT OLD TIME
C=================================================================EPILOG
C     BOUNDARY CONDITIONS
C-----------------------------------------------------------------EPILOG
C     PBCL = PRESSURE BC FOR LB, 0. : OFF 1. : ON
C     PBCR = PRESSURE BC FOR RB, 0. : OFF 1. : ON
C     PBCD = PRESSURE BC FOR DB, 0. : OFF 1. : ON
C     PBCF = PRESSURE BC FOR FB, 0. : OFF 1. : ON
C     PBCB = PRESSURE BC FOR BB, 0. : OFF 1. : ON
C     PBCT = PRESSURE BC FOR TB, 0. : OFF 1. : ON
C     SDNL = SPECIES DENSITY BC FOR LB
C     SDNR = SPECIES DENSITY BC FOR RB
C     SDND = SPECIES DENSITY BC FOR DB
C     SDNF = SPECIES DENSITY BC FOR FB
C     SDNB = SPECIES DENSITY BC FOR BB
C     SDNT = SPECIES DENSITY BC FOR TB
C     EDENL = BC FOR ROE AT LB
C     EDENR = BC FOR ROE AT RB
C     EDEND = BC FOR ROE AT DB
C     EDENF = BC FOR ROE AT FB
C     EDENB = BC FOR ROE AT BB
C     EDENT = BC FOR ROE AT TB
C     TEMPL = TEMPERATURE BC AT LB
C     TEMPR = TEMPERATURE BC AT RB
C     TEMPD = TEMPERATURE BC AT DB
C     TEMPF = TEMPERATURE BC AT FB
C     TEMPB = TEMPERATURE BC AT BB
C     TEMPT = TEMPERATURE BC AT TB
C     EDEEL = BC FOR ROEE AT LB
C     EDEER = BC FOR ROEE AT RB
C     EDEED = BC FOR ROEE AT DB
C     EDEEF = BC FOR ROEE AT FB
C     EDEEB = BC FOR ROEE AT BB
C     EDEET = BC FOR ROEE AT TB
C     TEEL = ELECTRON TEMPERATURE BC AT LB
C     TEER = ELECTRON TEMPERATURE BC AT RB
C     TEED = ELECTRON TEMPERATURE BC AT DB
C     TEEF = ELECTRON TEMPERATURE BC AT FB
C     TEEB = ELECTRON TEMPERATURE BC AT BB
C     TEET = ELECTRON TEMPERATURE BC AT TB
C     PRESL = PRESSURE BC AT LB
C     PRESR = PRESSURE BC AT RB
C     PRESD = PRESSURE BC AT DB
C     PRESF = PRESSURE BC AT FB
C     PRESB = PRESSURE BC AT BB
C     PREST = PRESSURE BC AT TB
C     UVELL = BC FOR U AT LB
C     UVELR = BC FOR U AT RB
C     UVELD = BC FOR U AT DB
C     UVELF = BC FOR U AT FB
C     UVELB = BC FOR U AT BB
C     UVELT = BC FOR U AT TB
C     VVELL = BC FOR V AT LB
C     VVELR = BC FOR V AT RB
C     VVELD = BC FOR V AT DB
C     VVELF = BC FOR V AT FB
C     VVELB = BC FOR V AT BB
C     VVELT = BC FOR V AT TB
C     WVELL = BC FOR W AT LB
C     WVELR = BC FOR W AT RB
C     WVELD = BC FOR W AT DB
C     WVELF = BC FOR W AT FB
C     WVELB = BC FOR W AT BB
C     WVELT = BC FOR W AT TB
C     TKEL = BC FOR TKE AT LB
C     TKER = BC FOR TKE AT RB
C     TKED = BC FOR TKE AT DB
C     TKEF = BC FOR TKE AT FB
C     TKEB = BC FOR TKE AT BB
C     TKET = BC FOR TKE AT TB
C     EPSL = BC FOR EPS AT LB
C     EPSR = BC FOR EPS AT RB
C     EPSD = BC FOR EPS AT DB
C     EPSF = BC FOR EPS AT FB
C     EPSB = BC FOR EPS AT BB
C     EPST = BC FOR EPS AT TB
C     IPBC = FLAG FOR VOLUME AVERAGE PRESSURE, 1 : PAMB
C=================================================================EPILOG
C     PRESSURE, ACCELERATION, AND DIVERGENCE
C-----------------------------------------------------------------EPILOG
C     P = PRESSURE
C     PN = P AT OLD TIME
C     Q = Q DEFINED IN EQ. (12) OF LAVA1
C     QN = Q AT OLD TIME
C     DIV = DIV(R*U)/R
C     DIVOLD = DIV AT OLD TIME
C     DIVE = NOT USED
C     UDELR = U*DEL(R)/R
C=================================================================EPILOG
C     STATE VARIABLES
C-----------------------------------------------------------------EPILOG
C     MW = MOLECULAR WEIGHT
C     RMW = 1/MW
C     GAMMA = SPECIFIC HEAT RATIO
C     EK = SPECIES SPECIFIC INTERNAL ENERGY
C     HK = SPECIES SPECIFIC ENTHALPY (KCAL/G-MOLE)
C     HTFORM = HEAT OF FORMATION (KCAL/G-MOLE), CONVERTED TO CGS LATER
C     QOM = ELECTRICAL CHARGE, CONVERTED TO CHARGE PER UNIT MASS LATER
C     IELC = SPECIES INDEX FOR ELECTRONS, = 0 IN ABSENCE OF ELECTRONS
C     IGAS = INDEX FOR GASEOUS PHASE, 0 : CONDENSED, 1 : GAS
C=================================================================EPILOG
C     EQUILIBRIUM CHEMISTRY VARIABLES
C-----------------------------------------------------------------EPILOG
C     OMGDOT = PROGRESS RATE
C=================================================================EPILOG
C     VARIABLES IN TURBULENCE MODELS
C-----------------------------------------------------------------EPILOG
C     ROTKER = RO*TKE*R
C     TKE = TURBULENT KINETIC ENERGY
C     TKEN = TKE AT OLD TIME
C     ROEPSR = RO*EPS*R
C     EPS = DISSIPATION RATE OF TURBULENT KINETIC ENERGY
C     EPSN = EPS AT OLD TIME
C     SGSL = LENGTH SCALE FOR SGS MODEL
C     WSDT = WS*DT, WS IS DEFINED IN KIVA1 AND KIVA2
C=================================================================EPILOG
C     PARTICLES
C-----------------------------------------------------------------EPILOG
C     RANB = SEED NUMBER FOR RANDOM NUMBER GENERATOR
C     RANS = SEED NUMBER FOR RANDOM NUMBER GENERATOR
C     TM1INJ = MASS OF PARTICLES INJECTED IN THE PREVIOUS TIME
C     TM2INJ = MASS OF PARTICLES INJECTED IN THE CURRENT TIME
C     RADP = EFFECTIVE PARTICLE RADIUS
C     PARTN = NUMBER OF REAL PARTICLES PER COMPUTATIONAL PARTICLE
C     PMSP = PARTIAL MASS OF REAL PARTICLE OF SPECIES IPSP
C     PMASS = MASS OF REAL PARTICLE
C     AREAP = SURFACE AREA OF REAL PARTICLE
C     XP = X COORDINATE OF PARTICLE
C     YP = Y COORDINATE OF PARTICLE
C     ZP = Z COORDINATE OF PARTICLE
C     UP = X COMPONENT OF PARTICLE VELOCITY
C     VP = Y COMPONENT OF PARTICLE VELOCITY
C     WP = Z COMPONENT OF PARTICLE VELOCITY
C     UTRB = X-COMPONENT TURBULENT FLUID VELOCITY SEEN BY PARTICLES
C     VTRB = Y-COMPONENT TURBULENT FLUID VELOCITY SEEN BY PARTICLES
C     WTRB = Z-COMPONENT TURBULENT FLUID VELOCITY SEEN BY PARTICLES
C            (SEE KIVA2 FOR DETAILS)
C     TURBT = TURBULENT TIME SCALE
C     TP = PARTICLE TEMPERATURE
C     EP = PARTICLE SPECIFIC INTERNAL ENERGY
C     DTPDEP = 1/(PARTICLE SPECIFIC HEAT)
C     TMM = MINIMUM MELTING TEMPERATURE
C     TML = MAXIMUM MELTING TEMPERATURE, TML = TMM FOR SINGLE COMPONENT
C     EMSSP = PARTICLE SURFACE TOTAL EMISSIVITY
C     RPSPHS = 1/PSPHS
C     RPSPHL = 1/PSPHL
C     EPM = PARTICLE SPECIFIC ENERGY AT TMM
C     EPL = PARTICLE SPECIFIC ENERGY AT TML = EPM + HLTNT
C     NP = NUMBER OF COMPUTATIONAL PARTICLES
C     ICP = INDEX OF THE CELL CONTAINING PARTICLE IP
C     ICNOZ = INDEX OF THE CELL CONTAINING INJECTION NOZZLE
C=================================================================EPILOG
C     TRANSPORT PROPERTIES
C-----------------------------------------------------------------EPILOG
C     VISC = TOTAL VISCOSITY FOR EACH CELL
C     COND = TRANSLATIONAL THERMAL CONDUCTIVITY OF EACH CELL
C     CONDE = ELECTRON THERMAL CONDUCTIVITY OF EACH CELL
C     RADLSS = VOLUMETRIC RADIATION LOSS OF EACH CELL
C     VIST = TURBULENT VISCOSITY FOR EACH CELL
C     DCOEF = DIFFUSION COEFFICIENTS FOR EACH CELL
C=================================================================EPILOG
C
C     VARIABLES DEFINED IN INPUT FILE, BLOCK DATA, AND DUMMY ARRAYS
C     ARE NOT SAVED IN DUMP
C
C=================================================================EPILOG
C
C     DUMMY ARRAYS
C                 .... NOT EXPLAINED
C=================================================================EPILOG
C     ARRAYS FOR SOLVING PARTICLE EQUATIONS
C-----------------------------------------------------------------EPILOG
C     RELVEL = RELATIVE VELOCITY OF PARTICLE AND FLUID
C     CD = PARTICLE DRAG COEFFICIENT
C     HTCO = PARTICLE HEAT TRANSFER COEFFICIENT
C     TSCALE = TURBULENCE TIME SCALE
C=================================================================EPILOG
C
C     VARIABLES DEFINED IN BLOCK DATA HOT
C
C=================================================================EPILOG
C     PHYSICAL CONSTANTS
C-----------------------------------------------------------------EPILOG
C     PI = 3.14159 26535 89793 23846
C     PIO2 = PI/2
C     PI2 = 2*PI
C     PI4 = 4*PI
C     PI4O3 = (4/3)*PI
C     PIO180 = PI/180
C     RGAS = UNIVERSAL GAS CONSTANT (ERG/(MOL*K))
C     AVOGAD = AVOGADRO'S NUMBER
C     ELECHG = ELECTRONIC CHARGE
C     VISRAT = VISCOSITY RATIO, SEE LAVA1
C     ERGCAL = KCAL TO ERG CONVERSION FACTOR
C     STEBOL = STEFAN-BOLTZMANN CONSTANT
C     BOLTZ = BOLTZMANN'S CONSTANT
C=================================================================EPILOG
C     OTHER PHYSICAL PARAMETERS
C-----------------------------------------------------------------EPILOG
C     TEMPMX = MAXIMUM ALLOWED TEMPERATURE IN STATE TABLES
C     GX = GRAVITY IN X DIRECTION
C     GY = GRAVITY IN Y DIRECTION
C     GZ = GRAVITY IN Z DIRECTION
C     PAMB = AMBIENT PRESSURE
C     TEMAMB = AMBIENT TEMPERATURE
C     ETA0 = CONSTANT USED FOR DIFFUSION COEFFICIENT, SEE APACHE REPORT
C     PRL = LAMINAR PRANDTL NUMBER
C     RPRT = 1/(TURBULENT PRANDTL NUMBER)
C     RSCT = 1/(TURBULENT SCHMIDT NUMBER)
C     CPS = CONSTANT USED IN TURBULENT DISPERSION MODEL
C=================================================================EPILOG
C     CONSTANTS USED IN TURBULENCE MODELS
C-----------------------------------------------------------------EPILOG
C     REYC = CRITICAL REYNOLDS NUMBER FOR WALL FUNCTION
C     CE1,CE2,CE3,CES,CMU = K-EPSILON MODEL CONSTANTS
C     RPRE = 1/PR FOR EPS DIFFUSION
C     SGSA,SGSD = SGS MODEL CONSTANTS
C     CE2CR,CMUCOR,AKEML1,AKEML2 = CONSTANTS USED IN K-EPSILON MODEL
C                                  CORRECTION IN AXISYMMETRIC FLOWS
C=================================================================EPILOG
C     CONTROL CONSTANTS USED IN CHEMISTRY
C-----------------------------------------------------------------EPILOG
C     TCHEMI = NOT USED
C     EPSCHM = CONVERGENCE TOLERANCE
C     OMGCHM = RELAXATION PARAMETER USED IN IMPLICIT CHEMISTRY
C     OMGCM2 = RELAXATION PARAMETER USED IN IMPLICIT CHEMISTRY
C=================================================================EPILOG
C     NUMBER OF MOLECULES FOR HETEROGENEOUS EQUILIBRIUM
C-----------------------------------------------------------------EPILOG
C     NGAS = FLAG FOR GASEOUS PHASE
C     NCNDNS = FLAG FOR CONDENSED PHASE
C=================================================================EPILOG
C     EQUILIBRIUM CHEMISTRY (NOT USED)
C-----------------------------------------------------------------EPILOG
C     CH4I1,CH4I2 = NOT USED
C=================================================================EPILOG
C     ACCELERATED EQUILIBRIUM CHEMISTRY VARIABLES (NOT USED)
C-----------------------------------------------------------------EPILOG
C     FRAC,NCMAX,MINVRT = NOT USED
C=================================================================EPILOG
C     SAFETY FACTORS USED IN TIME STEP CONTROL
C-----------------------------------------------------------------EPILOG
C     SAFEDT = SAFETY FACTOR FOR CONVECTION AND SPEED OF SOUND, <= 1.0
C     SAFDTD = SAFETY FACTOR FOR DIFFUSION, <= 1.0
C     DTGROW = LARGEST DT GROWTH FACTOR ALLOWED
C=================================================================EPILOG
C     NUMBERS
C-----------------------------------------------------------------EPILOG
C     SMALL = 1.0E-80
C     LARGE = 1.0E+100
C     ZERO = 0.0
C     ONE = 1.0
C     TWO = 2.0
C     THREE = 3.0
C     FOUR = 4.0
C     FIVE = 5.0
C     SIX = 6.0
C     SEVEN = 7.0
C     EIGHT = 8.0
C     NINE = 9.0
C     HALF = 0.5
C     PNTHRE = 0.3
C     PNTSIX = 0.6
C     PNTNIN = 0.9
C     ONEO3 = 1/3
C     TWOO3 = 2/3
C     FOURO3 = 4/3
C     FIVO3 = 5/3
C     THRHAF = 1.5
C     FIVHAF = 2.5
C     TEN = 10.0
C     TENTH = 0.1
C     HUNDRD = 100.0
C     HUNDTH = 0.01
C     THOUSD = 1000.0
C     THOUTH = 0.001
C     TWENTY = 20.0
C=================================================================EPILOG
C     MATHEMATICAL FUNCTIONS
C-----------------------------------------------------------------EPILOG
C     RERF = INVERSE OF ERROR FUNCTION
C=================================================================EPILOG
C     INPUT AND OUTPUT CONTROL
C-----------------------------------------------------------------EPILOG
C     IDUMP = MAKING RESTART FILE, 0 : OFF 1 : ON
C     NFDMP,NFRST,NFINP,NFOUT = UNITS FOR READ AND WRITE
C=================================================================EPILOG
C
C     VARIABLES DEFINED IN INPUT FILE AND NOT SAVED IN DUMP
C
C=================================================================EPILOG
C     PRESSURE AND ACCELERATION
C-----------------------------------------------------------------EPILOG
C     PGS = PGS SCALING PARAMETER, SEE LAVA1
C     RPGS2 = 1/(PGS*PGS)
C     DAMP,THETA,RELAX = CONSTANTS USED IN ACCELERATION METHOD DESCRIBED
C                        IN EQ. (12) OF LAVA1 AND SETQ
C     PQDIF = Q-P DEFINED IN EQ. (12) OF LAVA1
C     PREF = REFERENCE PRESSURE
C     MACCEL = OPTION NUMBER FOR ACCELERATION TECHNIQUES, SEE SETQ
C=================================================================EPILOG
C     RUN-TIME OPTION CONTROL
C-----------------------------------------------------------------EPILOG
C     DT = TIME STEP
C     DTJUMP = TIME STEP FOR GENERATING MOVIE FILES AND RESTART FILE
C     DTI = INITIAL DT
C     DTMAX = MAXIMUM DT ALLOWED
C     TMAX = MAXIMUM TIME
C     TIMPTL = STARTING TIME OF PARTICLE LOGIC <= MIN(T1INJ)
C     LDT = DT CONTROL OPTION, 0 : CONSTANT DT, 1 : AUTOMATIC DT CONTROL
C     JUMP = EVERY JUMP CYCLE, MESSAGES PRINTED ON THE SCREEN
C     NMAX = MAXIMUM CYCLE NUMBER
C=================================================================EPILOG
C     KINETIC CHEMISTRY VARIABLES
C-----------------------------------------------------------------EPILOG
C     AE = CONCENTRATION EXPONENTS IN FORWARD REACTION RATES
C     BE = CONCENTRATION EXPONENTS IN BACKWARD REACTION RATES
C     CHAEFF = CHAPERONE (THIRD BODY) EFFICIENCIES
C     AKS,BKS,CKS,DKS,EKS = PARAMETERS IN EQUILIBRIUM CONSTANT
C     ZETAF = TEMPERATURE EXPONENT IN FORWARD REACTION RATE COEFFICIENT
C     CF = PREEXPONENTIAL FACTOR FORWARD REACTION RATE COEFFICIENT
C     EF = ACTIVATION ENERGY IN FORWARD REACTION RATE COEFFICIENT
C     QR = NEGATIVE HEAT OF REACTION AT ABSOLUTE ZERO
C     FBMAM = FBM-FAM
C     FAM = FLOAT(AM)
C     FBM = FLOAT(BM)
C     FEK = FRACTION OF TOTAL CHEMICAL ENERGY RELEASE THAT GOES TO ELECTRONS
C     FRK = FRACTION OF TOTAL CHEMICAL ENERGY RELEASE LOST AS RADIATION
C     TFLAGK = 1. : REACTION RATES DEPEND ON ELECTRON TEMPERATURE
C              0. : REACTION RATES DEPEND ON HEAVY PARTICLE TEMPERATURE
C     TCUTL = LOWER CUT-OFF TEMPERATURE
C     TCUTH = UPPER CUT-OFF TEMPERATURE
C     NRK = NUMBER OF SLOW KINETIC CHEMICAL REACTIONS
C     NELEM = NUMBER OF SPECIES PARTICIPATING IN CHEMICAL REACTION
C     AM,BM,CM = STOICHIOMETRIC COEFFICIENTS
C=================================================================EPILOG
C     FAST KINETIC AND EQUILIBRIUM CHEMISTRY VARIABLES
C-----------------------------------------------------------------EPILOG
C     AS,BS,CS,DS,ES = PARAMETERS IN EQUILIBRIUM CONSTANT
C     FBNAN = FLOAT(BN-AN)
C     QEQ = NEGATIVE HEAT OF REACTION AT ABSOLUTE ZERO
C     TCUTEL = LOWER CUT-OFF TEMPERATURE
C     TCUTEH = UPPER CUT-OFF TEMPERATURE
C     CFE = PREEXPONENTIAL FACTOR FORWARD REACTION RATE COEFFICIENT
C     EFE = ACTIVATION ENERGY IN FORWARD REACTION RATE COEFFICIENT
C     ZETAFE = EXPONENT ON TEMPERATURE IN FORWARD REACTION RATE COEFFICIENT
C     FEE = FRACTION OF TOTAL CHEMICAL ENERGY RELEASE THAT GOES TO ELECTRONS
C     FRE = FRACTION OF TOTAL CHEMICAL ENERGY RELEASE LOST AS RADIATION
C     TFLAGE = 1. : REACTION RATES DEPEND ON ELECTRON TEMPERATURE
C              0. : REACTION RATES DEPEND ON HEAVY PARTICLE TEMPERATURE
C     NRE = NUMBER OF FAST KINETIC AND EQUILIBRIUM CHEMICAL REACTIONS
C     NLM = NUMBER OF SPECIES PARTICIPATING IN CHEMICAL REACTIONS
C     AN,BN,CN = STOICHIOMETRIC COEFFICIENTS
C=================================================================EPILOG
C     TURBULENCE MODELS
C-----------------------------------------------------------------EPILOG
C     ITURB = 0 : NO TURBULENCE, 1 : SGS MODEL, 2 : K-EPSILON MODEL
C     KECOR = AXISYMMETRIC CORRECTION FOR K-EPSILON, 0 : OFF, 1 : ON
C     LWALL = NOT USED
C=================================================================EPILOG
C     ARRAYS FOR PROPERTIES
C-----------------------------------------------------------------EPILOG
C     NCMP= NUMBER OF COMPONENT FOR PLASMA PROPERTIES, IN COML.h
C     VIS = VISCOSITY OF EACH COMPONENT AS FUNCTION OF TEMPERATURE
C     CND = TRANSLATIONAL THERMAL CONDUCTIVITY OF EACH COMPONENT
C     CNDE = ELECTRON THERMAL CONDUCTIVITY
C     SSUBR = VOLUMETRIC RADIATION LOSS OF EACH COMPONENT 
C     DCOFF = DIFFUSION COEFFICIENTS
C=================================================================EPILOG
C     PARTICLE INJECTION PARAMETERS
C-----------------------------------------------------------------EPILOG
C     XINJ = X COORDINATE OF PARTICLE INJECTION POINT
C     YINJ = Y COORDINATE OF PARTICLE INJECTION POINT
C     ZINJ = Z COORDINATE OF PARTICLE INJECTION POINT
C     ANOZ = AREA OF PARTICLE INJECTION NOZZLE
C     T1INJ = STARTING TIME OF PARTICLE INJECTION FOR EACH NOZZLE
C     CONE = FULL CONE ANGLE OF SPRAY (NOT HALF ANGLE) (DEGREE -> RADIAN)
C     TILTZ = SPRAY DIRECTION WITH RESPECT TO Z AXIS (DEGREE -> RADIAN)
C     TILTX = SPRAY DIRECTION WITH RESPECT TO X AXIS (DEGREE -> RADIAN)
C     EAVEC = AXIAL UNIT VECTOR FOR SPRAY NOZZLE
C     ENVEC = RADIAL UNIT VECTOR FOR SPRAY NOZZLE (NORMAL TO EAVEC)
C     EOVEC = RADIAL UNIT VECTOR FOR SPRAY NOZZLE (NORMAL TO EAVEC AND ENVEC)
C     TSPMAS = MASS INJECTION RATE
C     PMINJ = MASS PER COMPUTATIONAL PARTICLE
C     TPINJ = PARTICLE TEMPERATURE AT INJECTION POINT
C     VELINJ = AVERAGE INJECTION VELOCITY
C     VDISP = DISPERSION OF INJECTION VELOCITY
C     PYINJ = MASS FRACTION OF PARTICLE SPECIES IPSP
C     PXINJ = VOLUME FRACTION OF PARTICLE SPECIES IPSP
C     RPMIN = MINIMUM PARTICLE RADIUS
C     RPMAX = MAXIMUM PARTICLE RADIUS
C     PSZDIS = NUMBER OF PARTICLES IN EACH INTERVAL OF SIZE DISTRIBUTION
C     PSZINT = NORMALIZED INTEGRAL OF PSZDIS*RADP**3
C     PSZDEL = INTERVAL SIZE OF PARTICLE SIZE DISTRIBUTION
C     CARRYG = MASS FLOW RATE OF CARRIER GAS FOR EACH SPECIES
C     CRGAS = SUM OF CARRYG
C     CRMOMX = X DIRECTION MOMEMTUM SOURCE DUE TO CARRIER GAS
C     CRMOMY = Y DIRECTION MOMEMTUM SOURCE DUE TO CARRIER GAS
C     CRMOMZ = Z DIRECTION MOMEMTUM SOURCE DUE TO CARRIER GAS
C     CRENGY = ENERGY CARRIED BY CARRIER GAS
C     IPTCL = FLAG FOR PARTICLE LOGIC, 0 : OFF, 1 : ON
C     I3DP2D = 3-D PARTICLE SPRAY IN 2-D AXISYMMETRIC CALCULATION
C     NUMNOZ = NUMBER OF PARTICLE INJECTION NOZZLES
C     ICARRY = FLAG FOR CARRIER GAS, 0 : OFF, 1 : ON
C     NPSDIS = NUMBER OF INTERVALS IN PARTICLE SIZE DISTRIBUTION
C=================================================================EPILOG
C     PARTICLE MATERIAL PROPERTIES
C-----------------------------------------------------------------EPILOG
C     ROPI = MASS DENSITY OF PARTICLE
C     TMMI = MINIMUM MELTING TEMPERATURE
C     TMLI = MAXIMUM MELTING TEMPERATURE, TML = TMM FOR PURE SUBSTANCE
C     HLTNT = LATENT HEAT OF FUSION (CAL/G -> ERG/G)
C           = EP(TMLI) - EP(TMMI)
C             (FOR MIXTURES, T CHANGE IS INVOLVED IN MELTING)
C     PSPHS = SOLID PHASE SPECIFIC HEAT (CAL/(G*K) -> ERG/(G*K))
C     PSPHL = LIQUID PHASE SPECIFIC HEAT (CAL/(G*K) -> ERG/(G*K))
C     EMSSPI = PARTICLE SURFACE TOTAL EMISSIVITY
C=================================================================EPILOG
C
C     FREQUENTLY USED VARIABLES
C
C=================================================================EPILOG
C     I = CELL INDEX IN X DIRECTION
C     J = CELL INDEX IN Y DIRECTION
C     K = CELL INDEX IN Z DIRECTION
C     ICJ = ICK+(J-1)*NXT
C     ICK = (K-1)*NXYT
C     IC = CELL INDEX = I + ICJ
C     ISP = SPECIES INDEX
C     IT = TEMPERATURE INDEX FOR TABULATED PROPERTIES
C        = MIN(NIT1,INT(0.01*TEMP))
C     ICL = CELL INDEX OF LB GHOST CELL
C     ICR = CELL INDEX OF RB GHOST CELL
C     ICD = CELL INDEX OF DB GHOST CELL
C     ICF = CELL INDEX OF FB GHOST CELL
C     ICB = CELL INDEX OF BB GHOST CELL
C     ICT = CELL INDEX OF TB GHOST CELL
C     ICLR = CELL INDEX FOR LB AND RB USED FOR BC VARIABLES
C     ICDF = CELL INDEX FOR DB AND FB USED FOR BC VARIABLES
C     ICBT = CELL INDEX FOR BB AND TB USED FOR BC VARIABLES
C     IP = PARTICLE INDEX
C     IPSP = PARTICLE SPECIES INDEX
C     NPN = PARTICLE INDEX
C=================================================================EPILOG
C
C NEW VARIABLES, ARRAYS AND PARAMETERS INTRODUCED BY Y.P. WAN  08/28/98
C
C=================================================================EPILOG
C ----- NEW CONTROLING PARAMETERS IN INPUT FILE, ADDED IN COML.h
C     ICONDP = 0, NOT SOLVE THE HEAT CONDUCTION EQUATION FOR PARTCLE
C              1, SOLVE THE HEAT CONDUCTION EQUATION FOR PARTCLE
C     IEVAP = 0, WITHOUT PARTICLE EVAPORATION
C             1, WITH PARTICLE EVAPORATION
C     IPOST = 0, NO POSTPROCESSING FOR THIS RUN
C             1, POST-PROCESSING FOR THIS RUN
C     IFLUCT = 0, NOT CONSIDERING VOLTAGE FLUCTUATION
C              1, CONSIDERING VOLTAGE FLUCTUATION
C 
C ----- OLD LOCAL VARIABLE ADDED IN COML.h
C     CURCY =  CURRENCY (A)            
C     VOLTG =  VOLTAGE (VOLT)            
C     EFFCY =  EFFICIENCY OF THE GUN               
C     FLRT1 =  FLOW RATE OF PRIMARY GAS (SLM)               
C     FLRT2 =  FLOW RATE OF THE SECONDARY GAS (SLM)              
C     PWVEL =  POWER INDEX FOR THE EXIT VELOCITY RADIAL DISTRIBUTION             
C     PWTEP =  POWER INDEX FOR THE EXIT TEMPERATURE RADIAL DISTRIBUTION            
C     SWIRN =  SWIRL NUMBER FOR JET FLOW 
C
C ----- VARIABLES IN COMMPTC.h (FOR PARTICLE HEATING MODEL)
C     NGRID = ARRAY DIMENSION FOR ONE-D PARTICLE RADIAL VARIABLE
C     NHALF = ARRAY DIMENSION FOR A COMPUTATIONAL DOMAIN OF A SINGLE PHASE
C     NNP = ARRAY DIMENSION FOR NUMBER OF PARTICLES
C     MGD = GRID NUMBER FOR THE INNER DOMAIN (DOMAIN 1)(MOSTLY SOLID DOMAIN)
C     NGD = GRID NUMBER FOR THE INTERMEDIAT DOMAIN (DOMAIN 2) (USUALLY LIQUID)
C     LGD = GRID NUMBER FOR THE OUTER DOMAIN (DOMAIN 3)(USUALLY RESOLID)
C     NMGD = NGD+MGD+LGD, TOTAL NUMBER OF GRID
C     NCS = 0, FOR PLANE COORDINATE
C           1, FOR CYLINDRICAL CO.
C           2, FOR SPHERICAL CO.
C     Y1C(NHALF) = COORDINATES FOR GRID NODE (CENTER) OF DOMAIN 1
C     Y2C(NHALF) = COORDINATES FOR GRID NODE (CENTER) OF DOMAIN 2
C     Y3C(NHALF) = COORDINATES FOR GRID NODE (CENTER) OF DOMAIN 3
C     Y1B(NHALF) = COORDINATES FOR CONTROL VOLUME FACE (CENTER) OF DOMAIN 1
C     Y2B(NHALF) = COORDINATES FOR CONTROL VOLUME FACE (CENTER) OF DOMAIN 2
C     Y3B(NHALF) = COORDINATES FOR CONTROL VOLUME FACE (CENTER) OF DOMAIN 3
C     DLY1(NHALF) = LENGTH OF CONTROL VOLUME (DOMAIN 1)
C     DLY2(NHALF) = LENGTH OF CONTROL VOLUME (DOMAIN 2
C     DLY3(NHALF) = LENGTH OF CONTROL VOLUME (DOMAIN 3
C     TPCD(NNP,NGRID) = ARRAY STORING TEMPERATURE DISTRIBUTION
C     RD(NNP) = PARTICLE RADIUS
C     RM(NNP) = RADIUS OF MELT/SOLID INTERFACE
C     RRS(NNP) = RADIUS OF MELT/RESOLID INTERFACE
C     VI(NNP) = MOVING VELOCITY OF MELT/SOLID INTERFACE
C     VIRS(NNP) = MOVING VELOCITY OF MELT/RESOLID INTERFACE
C     SOLVS(NNP) = CONTROLING PARAMETER FOR THE SOLVING OF SOLID DOMAIN
C                  =1 SOLVE, =0, NOT SOLVE
C     SOLVL(NNP) = CONTROLING PARAMETER FOR THE SOLVING OF LIQUID DOMAIN
C                  =1 SOLVE, =0, NOT SOLVE
C     SOLVRS(NNP) = CONTROLING PARAMETER FOR THE SOLVING OF RESOLID DOMAIN
C                  =1 SOLVE, =0, NOT SOLVE 
C     DRD(NNP) = MOVING DISTANCE OF THE PARTICLE OUTER SURFACE WITHIN DT
C     PT1 = POWER INDEX FOR GRID FORMATION, DOMAIN 1
C     PT2 = POWER INDEX FOR GRID FORMATION, DOMAIN 2
C     PT3 = POWER INDEX FOR GRID FORMATION, DOMAIN 3
C
C ----- LOCAL VARIABLES USED IN SUBROUTINE PTCHEATING
C     IMKINE = SELECTION OF MELTING MODEL. =1, WITH KINETIC MODEL
C                                          =0, TEMP AT THE INTERFACE EQ. TMELT
C     IBOIL = INDICATOR FOR THE SURFACE TEMP, =1, IF THIS TEMP. REACHS BOILING POINT.
C                                             =0, OTHERWISE
C     MTYPE = INDICATING THE POWDER MATERIALS.
C     ITVI = ITERATION INDEX 
C     TG = TEMPERATURE OF GASPHASE AT THE LOCAL CELL
C     TPS = PARTICLE SURFACE TEMPERATURE
C     QCON = HEAT FLUX DUE TO CONVECTION
C     QRAD = HEAT FLUX DUE TO THERMAL RADIATION
C     QEVAP = HEAT FLUX NEEDED FOR EVAPORATION
C     DMPTC = AMOUNT OF MASS EVAPORATED FROM THE PARTICLE
C     TAMB = TEMPERATURE OF AMBIENT AIR, (USUALLY ROOM TEMP.)
C     TMIDS(NHALF) = ARRAY FOR TEMPORARY STORAGE OF TEMPERATURE IN SOLID DOMAIN
C     TMIDL(NHALF) = ARRAY FOR TEMPORARY STORAGE OF TEMPERATURE IN LIQUID DOMAIN
C     TMIDRS(NHALF) = ARRAY FOR TEMPORARY STORAGE OF TEMPERATURE IN RESOLID DOMAIN
C     AP(NHALF) = COEFFICIENT IN ALGEBRAIC EQUATIONS
C     AE(NHALF) = COEFFICIENT IN ALGEBRAIC EQUATIONS
C     AW(NHALF) = COEFFICIENT IN ALGEBRAIC EQUATIONS
C     BB(NHALF) = COEFFICIENT IN ALGEBRAIC EQUATIONS
C     SP(NHALF) = LINEARLIZED SOURCE TERM IN ALGEBRAIC EQUATIONS
C     SC(NHALF) = LINEARLIZED SOURCE TERM IN ALGEBRAIC EQUATIONS
C     TMELT = MELTING TEMPERATURE
C     DRM = MOVING DISTANCE OF THE MELT/SOLID INTERFACE
C     RMTMP = TEMPORARY STORAGE OF RADIUS OF MELT/SOLID INTERFACE
C     DRS = MOVING DISTANCE OF THE MELT/RESOLID INTERFACE
C     RSTMP = TEMPORARY STORAGE OF RADIUS OF MELT/RESOLID INTERFACE
C     YYC = TEMPORARY VARIABLE
C     RJ = TEMPORARY VARIABLE
C     RJ1 = TEMPORARY VARIABLE
C     FLUXL = HEAT FLUX FROM LIQUID TO THE INTERFACE
C     FLUXS = HEAT FLUX FROM SOLID TO THE INTERFACE
C     VIMID = TEMPORARY STORAGE FOR INTERFACE MOVING VELOCITY
C     EPS = A SMALL VALUE
C     DVI = AJUSTED VELOCITY
C     RELAX = RELAXATION FACTOR
C     LATM = LATENT HEAT OF FUSION
C     MUI = COEFFICIENT FOR MELTING INTERFACE MOVING
C     TMI = TEMPERATURE AT THE MELTING INTERFACE
C     DTT = DT WITHIN THE SUBLEVEL IF NEEDED
C     DT0 = REMAINING TIME 
C     DRMMIN = MINIMUM GRID SIZE TO LIMIT THE INTERFACE MOVING DISTANCE
C     STBOL = STEFAN-BOLTZMAN CONSTANT
C     EMISS = EMISSIVITY OF PARTICLE SURFACE
C
C ----- LOCAL VARIBLES IN SUBROUTINE LAVA FOR VOLTAGE FLUCTUATION
C     VOLTMAX = MAXIMUM VOLTAGE 
C     VOLTMIN = MINIMUM VOLTAGE 
C     TPERIOD = PERIODIC DURATION OF FLUCTUATION
C     DTNVOL = TIME INCREMENT
C     TNTIM = TIME CORRESPONDING TO N FLUCTUATION CYCLES
C     VOLTNEW = NEW VOLTAGE AT THE TIME
C     TIMNVOL = TIME WITHIN A FLUCTUATION CYCLE
C
