/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import costoptiontree.CostOption;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JSlider;

/**
 *
 * @author Michael
 */
public class CostOptionView extends javax.swing.JPanel implements ActionListener{
    
    private CostOption option;
    private boolean isOptionSet = false;
    /**
     * Creates new form CostOptionView
     */
    public CostOptionView() {
        initComponents();
        jTextArea_description.setLineWrap(true);
    }

    public CostOption getOption() {
        return option;
    }

    public void setOption(CostOption option) {
        this.option = option;
        isOptionSet = true;
        
        jLabel_label.setText(option.getLabel());
        jTextArea_description.append(option.getDescription());
        
        jLabel_scaledMax.setText(new Integer(option.getScaledMaxCost()).toString());
        jLabel_scaledMin.setText(new Integer(option.getScaledMinCost()).toString());
        
        jSlider_cost.setMaximum(option.getMaxCost());
        jSlider_cost.setMinimum(option.getMinCost());
        
        jSlider_cost.setValue(option.getSelectedCost());
        
        jLabel_unitMax.setText(new Integer(option.getMaxCost()).toString());
        jLabel_unitMin.setText(new Integer(option.getMinCost()).toString());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_descriptionScrollPane = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jLabel_label = new javax.swing.JLabel();
        jSlider_cost = new javax.swing.JSlider();
        jLabel_scaledMin = new javax.swing.JLabel();
        jLabel_scaledMax = new javax.swing.JLabel();
        jLabel_unitMin = new javax.swing.JLabel();
        jLabel_unitMax = new javax.swing.JLabel();
        jLabel_scaledSelected = new javax.swing.JLabel();
        jLabel_unitSelected = new javax.swing.JLabel();
        jLabel_scaled = new javax.swing.JLabel();
        jLabel_unit = new javax.swing.JLabel();

        jTextArea_description.setEditable(false);
        jTextArea_description.setColumns(20);
        jTextArea_description.setRows(5);
        jScrollPane_descriptionScrollPane.setViewportView(jTextArea_description);

        jLabel_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_label.setText("label");

        jSlider_cost.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_costStateChanged(evt);
            }
        });

        jLabel_scaledMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scaledMin.setText("scaledMin");

        jLabel_scaledMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scaledMax.setText("scaledMax");

        jLabel_unitMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_unitMin.setText("unitMin");

        jLabel_unitMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_unitMax.setText("unitMax");

        jLabel_scaledSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scaledSelected.setText("scaledSelected");

        jLabel_unitSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_unitSelected.setText("unitSelected");

        jLabel_scaled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_scaled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scaled.setText("scaled");

        jLabel_unit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_unit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_unit.setText("unit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_scaledMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_scaledSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_scaledMax))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_unitMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_unitSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_unitMax)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_scaled)
                    .addComponent(jLabel_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_descriptionScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_scaledMin)
                            .addComponent(jLabel_scaledMax)
                            .addComponent(jLabel_scaledSelected)
                            .addComponent(jLabel_scaled))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_unitMin)
                            .addComponent(jLabel_unitMax)
                            .addComponent(jLabel_unitSelected)
                            .addComponent(jLabel_unit)))
                    .addComponent(jLabel_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_costStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_costStateChanged
        int value = jSlider_cost.getValue();

        JSlider source = (JSlider)evt.getSource();
        if (!source.getValueIsAdjusting()) {
            int selectedCost = (int)source.getValue();
            
            if (isOptionSet){
                option.setSelectedCost(selectedCost);
                jLabel_unitSelected.setText(new Integer(option.getSelectedCost()).toString());
                jLabel_scaledSelected.setText(new Integer(option.getScaledCost()).toString());
            }
        }
    }//GEN-LAST:event_jSlider_costStateChanged

    @Override
    public void actionPerformed(ActionEvent evt) {
        System.out.println("actionPerformed in CostOptionView: "+evt.getActionCommand());
        if (!isOptionSet){
            return;
        }

        if (BaseComponentListWithDeleteButtons.actionDeleteComponent.equals(evt.getActionCommand())) {
            System.out.println("deleting option");
            delete();
        } 
    }
    
    public void delete(){
        
        if (option.getParent()==null){
            return;
        }
        option.getParent().removeCostOption(option);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_label;
    private javax.swing.JLabel jLabel_scaled;
    private javax.swing.JLabel jLabel_scaledMax;
    private javax.swing.JLabel jLabel_scaledMin;
    private javax.swing.JLabel jLabel_scaledSelected;
    private javax.swing.JLabel jLabel_unit;
    private javax.swing.JLabel jLabel_unitMax;
    private javax.swing.JLabel jLabel_unitMin;
    private javax.swing.JLabel jLabel_unitSelected;
    private javax.swing.JScrollPane jScrollPane_descriptionScrollPane;
    private javax.swing.JSlider jSlider_cost;
    private javax.swing.JTextArea jTextArea_description;
    // End of variables declaration//GEN-END:variables
}
