/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

/**
 *
 * @author Michael
 */
public class CostSummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CostSummaryPanel
     */
    public CostSummaryPanel() {
        initComponents();
    }
    
    public void displayCost(int cost){
        jLabel_displayTotalCost.setText(""+cost);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_costSummary = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_displayTotalCost = new javax.swing.JLabel();

        jLabel_costSummary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_costSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_costSummary.setText("Cost Summary");

        jLabel7.setText("totalCost,$");

        jLabel_displayTotalCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_displayTotalCost.setText("##");
        jLabel_displayTotalCost.setBorder(javax.swing.BorderFactory.createBevelBorder(1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_costSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_displayTotalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_costSummary)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_displayTotalCost))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_costSummary;
    private javax.swing.JLabel jLabel_displayTotalCost;
    // End of variables declaration//GEN-END:variables
}
